# Generated by Django 5.2.5 on 2025-08-20 01:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='display_name',
        ),
        migrations.AddField(
            model_name='pixel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pixel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='game_api.player'),
        ),
        migrations.AddField(
            model_name='pixel',
            name='planted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2001, 9, 11, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
