# Generated by Django 5.2.5 on 2025-08-25 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_remove_player_display_name_pixel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='level',
        ),
        migrations.AddField(
            model_name='pixel',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='game_api.player'),
        ),
    ]
