# Generated by Django 5.2.5 on 2025-08-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_remove_player_level_pixel_total_xp_alter_pixel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seeds',
            field=models.IntegerField(default=3),
        ),
    ]
