# Generated by Django 5.2.5 on 2025-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0004_player_seeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='y',
            field=models.FloatField(),
        ),
    ]
